"select * from students"
"SELECT name from students"
"SELECT * FROM students WHERE Age>30"
"SELECT name FROM students WHERE Gender='F' AND Age>30"
"SELECT Points FROM students WHERE name  = 'Alex'"
"INSERT INTO students (Name, Age,Points,Gender) VALUES ('Michel',26,1000,'M')"
"UPDATE students SET Points = Points +20 WHERE name = 'Basma'"
"UPDATE students SET Points = Points -10 WHERE name = 'Alex'"